version: "3"

services:
  mysql:
    build: ./mysql/
    restart: always
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    restart: always
  backend:
    build: ./backend/
    restart: always
  algorithm:
    build: ./algorithm/
    restart: always
  