name: build-upload

on:
  release:
    types: [published]

jobs:
  linux-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Setup tag info
        run: |
          GIT_TAG=${GITHUB_REF#refs/*/}
          echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Build Project
        run: |
          mkdir -p release
          chmod 777 ./tools/release.sh
          ./tools/release.sh

      - name: tar files
        run: |
          mkdir -p publish
          tar czvf $GITHUB_WORKSPACE/publish/StaticAnalyzer-${{ env.GIT_TAG }}-linux.tar.gz ./release/

      - name: Upload image to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          file: 'publish/*.tar.gz'
          file_glob: true
          tag: ${{ env.GIT_TAG }}
          overwrite: true
